# Generated by Django 5.2 on 2025-08-08 08:54

import _applib.model_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30)),
                ('customer_phone', models.CharField(max_length=11, unique=True, validators=[_applib.model_utils.PhoneValidator()])),
                ('customer_email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True, validators=[_applib.model_utils.DOBValidator()])),
                ('status', models.BooleanField(choices=[('True', 'Active'), ('False', 'Inactive')], default='True', max_length=15)),
                ('password', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customer',
            },
        ),
    ]
