# Generated by Django 5.2 on 2025-08-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_model',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
