# Generated by Django 5.2 on 2025-08-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0002_alter_customer_model_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_model',
            name='address',
            field=models.TextField(default='Not provided'),
        ),
    ]
