# Generated by Django 5.2 on 2025-08-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0003_customer_model_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_model',
            name='address',
            field=models.TextField(),
        ),
    ]
