# Generated by Django 5.2 on 2025-08-08 14:29

import _applib.model_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resturant_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resturant_name', models.CharField(max_length=30)),
                ('resturant_phone', models.CharField(max_length=11, unique=True, validators=[_applib.model_utils.PhoneValidator()])),
                ('resturant_email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TimeField()),
                ('founded_on', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resturant',
                'verbose_name_plural': 'Resturants',
                'db_table': 'resturant',
            },
        ),
    ]
