# Generated by Django 5.2 on 2025-08-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resturant_model',
            name='address',
            field=models.TextField(max_length=256),
        ),
    ]
