# Generated by Django 5.2 on 2025-08-11 15:27

import _applib.model_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food_Items_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resturant_phone', models.CharField(max_length=11, unique=True, validators=[_applib.model_utils.PhoneValidator()])),
                ('food_items_name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=256)),
                ('price', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Food Item',
                'verbose_name_plural': 'Food Items',
                'db_table': 'food_items',
            },
        ),
    ]
